import { TransferType } from '../screens/TransferSelectionScreen';

export type ProfileStackParamList = {
  ProfileMain: undefined;
  AdminCategories: undefined;
  AdminAnalytics: undefined;
  BoostManagement: undefined;
  RealTimeMonitoring: undefined;
  UserManagement: undefined;
  ProductModeration: undefined;
  AdvancedAnalytics: undefined;
  FinancialReports: undefined;
  PlatformSettings: undefined;
  RoleManagement: undefined;
  SecurityAudit: undefined;
  GDPRCompliance: undefined;
  NotificationsManagement: undefined;
  SupportTickets: undefined;
  SystemMaintenance: undefined;
  APIManagement: undefined;
  PaymentManagement: undefined;
  SubscriptionManagement: undefined;
  MarketingPromotions: undefined;
  SEOOptimization: undefined;
  DynamicFormsManagement: undefined;
  DynamicFormFields: { formId: number; formName: string };
  MyProducts: undefined;
  MyProductDetail: { productId: string };
  EditProduct: { productId: string };
  Wallet: undefined;
  EditProfile: undefined;
  MyAnnouncements: undefined;
  Transactions: undefined;
  Orders: undefined;
  EmailSettings: undefined;
  PaymentMethods: undefined;
  NotificationSettings: undefined;
  BulkDiscount: undefined;
  TransferSelection: undefined;
  TransferAmount: { transferType: TransferType };
  TransferConfirmation: {
    transferType: TransferType;
    amount: number;
    fee: number;
    totalAmount: number;
  };
  TransferSuccess: {
    transferType: TransferType;
    amount: number;
    fee: number;
    totalAmount: number;
    transactionId: string;
  };
}; 